{
  config,
  lib,
  pkgs,
  ...
}:

let
  tmuxConfigDirectory = "${config.home.homeDirectory}/tmux-config";
  tmuxConfigFile = "${tmuxConfigDirectory}/.tmux.conf";
  tmuxLocalConfigFile = "${tmuxConfigDirectory}/.tmux.conf.local";
  resurrectPlugin = "${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect";
  continuumPlugin = "${pkgs.tmuxPlugins.continuum}/share/tmux-plugins/continuum";
  sessionxPlugin = "${pkgs.tmuxPlugins.tmux-sessionx}/share/tmux-plugins/sessionx";
  nixPluginConfig = pkgs.writeText "tmux-nix-plugins.conf" ''
    # Generated by Home Manager. Plugin revisions follow the locked nixpkgs input.
    run-shell ${lib.escapeShellArg "${resurrectPlugin}/resurrect.tmux"}
    run-shell ${lib.escapeShellArg "${continuumPlugin}/continuum.tmux"}
    run-shell ${lib.escapeShellArg "${sessionxPlugin}/sessionx.tmux"}
    bind-key -n M-s run-shell -b ${lib.escapeShellArg "${sessionxPlugin}/scripts/sessionx.sh"}
  '';
in
{
  home.activation.checkExternalTmuxConfig = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    if [[ ! -r ${lib.escapeShellArg tmuxConfigFile} ]]; then
      echo "Missing external tmux config: ${tmuxConfigFile}" >&2
      exit 1
    fi

    if [[ ! -r ${lib.escapeShellArg tmuxLocalConfigFile} ]]; then
      echo "Missing external tmux config: ${tmuxLocalConfigFile}" >&2
      exit 1
    fi
  '';

  home.file.".tmux.conf".source = config.lib.file.mkOutOfStoreSymlink tmuxConfigFile;

  home.file.".tmux.conf.local".source = config.lib.file.mkOutOfStoreSymlink tmuxLocalConfigFile;

  xdg.configFile."tmux/nix-plugins.conf".source = nixPluginConfig;
}
